version: '3.1'

services:

  db:
    image: postgres
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: -NQI2tIM?|G>B@A2
      POSTGRES_DB: all-sounds
  
  server:
    build:
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ENV=${ENV}